language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
  - "node_modules"
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
before_install:
  - npm install -g node-gyp
  - npm run init:test
