language: node_js
node_js:
  - "lts/*"
  - "node"
services:
  - mysql
cache:
  directories:
  - "node_modules"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS chat_test;'
  - npm run init:test
